version: '3.4'

services:
  run:
    build:
      context: ./
    entrypoint: /opt/github-history-generator/run.py
    volumes:
      - "${PWD}/:/opt/github-history-generator"
    working_dir: /opt/github-history-generator

  migration:
    build:
      context: ./
    entrypoint: /opt/github-history-generator/migration.py
    volumes:
      - "${PWD}/:/opt/github-history-generator"
    working_dir: /opt/github-history-generator
